# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54d0efe482ae70862edac055441bbb9ca35b0796dc7709e27042192579e4b83d36175d48b9d43a533da2218c280c585825803c9dfcfe14c159266baab79d2e5e

test:
  secret_key_base: cd9808d314b7c91e8819cd3e8d127f906ac26f9b7cdf6edaba5ea76f4d8102512db06928f14d010012c729c95e980ed9391f15dd4e18e6216969d77b06c96875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
